version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    groups:
      go-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
      go-security:
        applies-to: security-updates
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    groups:
      actions:
        applies-to: version-updates
        patterns: ["*"]
      actions-security:
        applies-to: security-updates
        patterns: ["*"]
    commit-message:
      prefix: "chore(ci)"
