// Code generated from api/openapi.upstream.yaml; DO NOT EDIT.
package api

// Operation describes an upstream API endpoint.
type Operation struct{ ID, Method, Path, Summary string }

var operations = map[string]Operation{
	"acceptDeviceInvite": {ID: "acceptDeviceInvite", Method: "POST", Path: "/device-invites/-/accept", Summary: "Accept a device invite"},
	"approveUser":        {ID: "approveUser", Method: "POST", Path: "/users/{userId}/approve", Summary: "Approve a user"},
	"authorizeDevice":    {ID: "authorizeDevice", Method: "POST", Path: "/device/{deviceId}/authorized", Summary: "Authorize device"},
	"batchUpdateCustomDevicePostureAttributes": {ID: "batchUpdateCustomDevicePostureAttributes", Method: "PATCH", Path: "/tailnet/{tailnet}/device-attributes", Summary: "Batch update custom device posture attributes"},
	"createDeviceInvites":                      {ID: "createDeviceInvites", Method: "POST", Path: "/device/{deviceId}/device-invites", Summary: "Create device invites"},
	"createKey":                                {ID: "createKey", Method: "POST", Path: "/tailnet/{tailnet}/keys", Summary: "Create an auth key or trust credential"},
	"createOAuthApp":                           {ID: "createOAuthApp", Method: "POST", Path: "/tailnet/{tailnet}/oauth-apps", Summary: "Create an OAuth app"},
	"createOrganizationTailnet":                {ID: "createOrganizationTailnet", Method: "POST", Path: "/organizations/{organization}/tailnets", Summary: "Create a tailnet"},
	"createPostureIntegration":                 {ID: "createPostureIntegration", Method: "POST", Path: "/tailnet/{tailnet}/posture/integrations", Summary: "Create a posture integration"},
	"createUserInvites":                        {ID: "createUserInvites", Method: "POST", Path: "/tailnet/{tailnet}/user-invites", Summary: "Create user invites"},
	"createWebhook":                            {ID: "createWebhook", Method: "POST", Path: "/tailnet/{tailnet}/webhooks", Summary: "Create a webhook"},
	"deleteCustomDevicePostureAttributes":      {ID: "deleteCustomDevicePostureAttributes", Method: "DELETE", Path: "/device/{deviceId}/attributes/{attributeKey}", Summary: "Delete custom device posture attributes"},
	"deleteDevice":                             {ID: "deleteDevice", Method: "DELETE", Path: "/device/{deviceId}", Summary: "Delete a device"},
	"deleteDeviceInvite":                       {ID: "deleteDeviceInvite", Method: "DELETE", Path: "/device-invites/{deviceInviteId}", Summary: "Delete a device invite"},
	"deleteKey":                                {ID: "deleteKey", Method: "DELETE", Path: "/tailnet/{tailnet}/keys/{keyId}", Summary: "Delete key"},
	"deleteOAuthApp":                           {ID: "deleteOAuthApp", Method: "DELETE", Path: "/tailnet/{tailnet}/oauth-apps/{appId}", Summary: "Delete OAuth app"},
	"deletePostureIntegration":                 {ID: "deletePostureIntegration", Method: "DELETE", Path: "/posture/integrations/{id}", Summary: "Delete a posture integration"},
	"deleteService":                            {ID: "deleteService", Method: "DELETE", Path: "/tailnet/{tailnet}/services/{serviceName}", Summary: "Delete a Service"},
	"deleteTailnet":                            {ID: "deleteTailnet", Method: "DELETE", Path: "/tailnet/{tailnet}", Summary: "Delete a tailnet"},
	"deleteUser":                               {ID: "deleteUser", Method: "POST", Path: "/users/{userId}/delete", Summary: "Delete a user"},
	"deleteUserInvite":                         {ID: "deleteUserInvite", Method: "DELETE", Path: "/user-invites/{userInviteId}", Summary: "Delete a user invite"},
	"deleteWebhook":                            {ID: "deleteWebhook", Method: "DELETE", Path: "/webhooks/{endpointId}", Summary: "Delete webhook"},
	"disableLogStreaming":                      {ID: "disableLogStreaming", Method: "DELETE", Path: "/tailnet/{tailnet}/logging/{logType}/stream", Summary: "Disable log streaming"},
	"expireDeviceKey":                          {ID: "expireDeviceKey", Method: "POST", Path: "/device/{deviceId}/expire", Summary: "Expire a device's key"},
	"getAwsExternalId":                         {ID: "getAwsExternalId", Method: "POST", Path: "/tailnet/{tailnet}/aws-external-id", Summary: "Create or get AWS external id"},
	"getContacts":                              {ID: "getContacts", Method: "GET", Path: "/tailnet/{tailnet}/contacts", Summary: "Get contacts"},
	"getDevice":                                {ID: "getDevice", Method: "GET", Path: "/device/{deviceId}", Summary: "Get a device"},
	"getDeviceInvite":                          {ID: "getDeviceInvite", Method: "GET", Path: "/device-invites/{deviceInviteId}", Summary: "Get a device invite"},
	"getDevicePostureAttributes":               {ID: "getDevicePostureAttributes", Method: "GET", Path: "/device/{deviceId}/attributes", Summary: "Get device posture attributes"},
	"getDnsConfiguration":                      {ID: "getDnsConfiguration", Method: "GET", Path: "/tailnet/{tailnet}/dns/configuration", Summary: "Get DNS configuration"},
	"getDnsPreferences":                        {ID: "getDnsPreferences", Method: "GET", Path: "/tailnet/{tailnet}/dns/preferences", Summary: "Get DNS preferences"},
	"getKey":                                   {ID: "getKey", Method: "GET", Path: "/tailnet/{tailnet}/keys/{keyId}", Summary: "Get key"},
	"getLogStreamingConfiguration":             {ID: "getLogStreamingConfiguration", Method: "GET", Path: "/tailnet/{tailnet}/logging/{logType}/stream", Summary: "Get log streaming configuration"},
	"getLogStreamingStatus":                    {ID: "getLogStreamingStatus", Method: "GET", Path: "/tailnet/{tailnet}/logging/{logType}/stream/status", Summary: "Get log streaming status"},
	"getOAuthApp":                              {ID: "getOAuthApp", Method: "GET", Path: "/tailnet/{tailnet}/oauth-apps/{appId}", Summary: "Get OAuth app"},
	"getPolicyFile":                            {ID: "getPolicyFile", Method: "GET", Path: "/tailnet/{tailnet}/acl", Summary: "Get policy file"},
	"getPostureIntegration":                    {ID: "getPostureIntegration", Method: "GET", Path: "/posture/integrations/{id}", Summary: "Get a posture integration"},
	"getPostureIntegrations":                   {ID: "getPostureIntegrations", Method: "GET", Path: "/tailnet/{tailnet}/posture/integrations", Summary: "List all posture integrations"},
	"getService":                               {ID: "getService", Method: "GET", Path: "/tailnet/{tailnet}/services/{serviceName}", Summary: "Get a Service"},
	"getServiceDeviceApproval":                 {ID: "getServiceDeviceApproval", Method: "GET", Path: "/tailnet/{tailnet}/services/{serviceName}/device/{deviceId}/approved", Summary: "Get approval status of Service on a device"},
	"getSplitDns":                              {ID: "getSplitDns", Method: "GET", Path: "/tailnet/{tailnet}/dns/split-dns", Summary: "Get split DNS"},
	"getTailnetSettings":                       {ID: "getTailnetSettings", Method: "GET", Path: "/tailnet/{tailnet}/settings", Summary: "Get tailnet settings"},
	"getUser":                                  {ID: "getUser", Method: "GET", Path: "/users/{userId}", Summary: "Get a user"},
	"getUserInvite":                            {ID: "getUserInvite", Method: "GET", Path: "/user-invites/{userInviteId}", Summary: "Get a user invite"},
	"getWebhook":                               {ID: "getWebhook", Method: "GET", Path: "/webhooks/{endpointId}", Summary: "Get webhook"},
	"listConfigurationAuditLogs":               {ID: "listConfigurationAuditLogs", Method: "GET", Path: "/tailnet/{tailnet}/logging/configuration", Summary: "List configuration audit logs"},
	"listDeviceInvites":                        {ID: "listDeviceInvites", Method: "GET", Path: "/device/{deviceId}/device-invites", Summary: "List device invites"},
	"listDeviceRoutes":                         {ID: "listDeviceRoutes", Method: "GET", Path: "/device/{deviceId}/routes", Summary: "List device routes"},
	"listDnsNameservers":                       {ID: "listDnsNameservers", Method: "GET", Path: "/tailnet/{tailnet}/dns/nameservers", Summary: "List DNS nameservers"},
	"listDnsSearchPaths":                       {ID: "listDnsSearchPaths", Method: "GET", Path: "/tailnet/{tailnet}/dns/searchpaths", Summary: "List DNS search paths"},
	"listNetworkFlowLogs":                      {ID: "listNetworkFlowLogs", Method: "GET", Path: "/tailnet/{tailnet}/logging/network", Summary: "List network flow logs"},
	"listOAuthApps":                            {ID: "listOAuthApps", Method: "GET", Path: "/tailnet/{tailnet}/oauth-apps", Summary: "List OAuth apps"},
	"listOrganizationTailnets":                 {ID: "listOrganizationTailnets", Method: "GET", Path: "/organizations/{organization}/tailnets", Summary: "List tailnets"},
	"listServiceHosts":                         {ID: "listServiceHosts", Method: "GET", Path: "/tailnet/{tailnet}/services/{serviceName}/devices", Summary: "List devices hosting a Service"},
	"listServices":                             {ID: "listServices", Method: "GET", Path: "/tailnet/{tailnet}/services", Summary: "List all Services"},
	"listTailnetDevices":                       {ID: "listTailnetDevices", Method: "GET", Path: "/tailnet/{tailnet}/devices", Summary: "List tailnet devices"},
	"listTailnetKeys":                          {ID: "listTailnetKeys", Method: "GET", Path: "/tailnet/{tailnet}/keys", Summary: "List tailnet keys"},
	"listUserInvites":                          {ID: "listUserInvites", Method: "GET", Path: "/tailnet/{tailnet}/user-invites", Summary: "List user invites"},
	"listUsers":                                {ID: "listUsers", Method: "GET", Path: "/tailnet/{tailnet}/users", Summary: "List users"},
	"listWebhooks":                             {ID: "listWebhooks", Method: "GET", Path: "/tailnet/{tailnet}/webhooks", Summary: "List webhooks"},
	"previewRuleMatches":                       {ID: "previewRuleMatches", Method: "POST", Path: "/tailnet/{tailnet}/acl/preview", Summary: "Preview rule matches"},
	"resendContactVerificationEmail":           {ID: "resendContactVerificationEmail", Method: "POST", Path: "/tailnet/{tailnet}/contacts/{contactType}/resend-verification-email", Summary: "Resend verification email"},
	"resendDeviceInvite":                       {ID: "resendDeviceInvite", Method: "POST", Path: "/device-invites/{deviceInviteId}/resend", Summary: "Resend a device invite"},
	"resendUserInvite":                         {ID: "resendUserInvite", Method: "POST", Path: "/user-invites/{userInviteId}/resend", Summary: "Resend a user invite"},
	"restoreUser":                              {ID: "restoreUser", Method: "POST", Path: "/users/{userId}/restore", Summary: "Restore a user"},
	"rotateWebhookSecret":                      {ID: "rotateWebhookSecret", Method: "POST", Path: "/webhooks/{endpointId}/rotate", Summary: "Rotate webhook secret"},
	"setCustomDevicePostureAttributes":         {ID: "setCustomDevicePostureAttributes", Method: "POST", Path: "/device/{deviceId}/attributes/{attributeKey}", Summary: "Set custom device posture attributes"},
	"setDeviceIp":                              {ID: "setDeviceIp", Method: "POST", Path: "/device/{deviceId}/ip", Summary: "Set device IPv4 address"},
	"setDeviceName":                            {ID: "setDeviceName", Method: "POST", Path: "/device/{deviceId}/name", Summary: "Set device name"},
	"setDeviceRoutes":                          {ID: "setDeviceRoutes", Method: "POST", Path: "/device/{deviceId}/routes", Summary: "Set device routes"},
	"setDeviceTags":                            {ID: "setDeviceTags", Method: "POST", Path: "/device/{deviceId}/tags", Summary: "Set device tags"},
	"setDnsConfiguration":                      {ID: "setDnsConfiguration", Method: "POST", Path: "/tailnet/{tailnet}/dns/configuration", Summary: "Set DNS configuration"},
	"setDnsNameservers":                        {ID: "setDnsNameservers", Method: "POST", Path: "/tailnet/{tailnet}/dns/nameservers", Summary: "Set DNS nameservers"},
	"setDnsPreferences":                        {ID: "setDnsPreferences", Method: "POST", Path: "/tailnet/{tailnet}/dns/preferences", Summary: "Set DNS preferences"},
	"setDnsSearchPaths":                        {ID: "setDnsSearchPaths", Method: "POST", Path: "/tailnet/{tailnet}/dns/searchpaths", Summary: "Set DNS search paths"},
	"setKey":                                   {ID: "setKey", Method: "PUT", Path: "/tailnet/{tailnet}/keys/{keyId}", Summary: "Set key"},
	"setLogStreamingConfiguration":             {ID: "setLogStreamingConfiguration", Method: "PUT", Path: "/tailnet/{tailnet}/logging/{logType}/stream", Summary: "Set log streaming configuration"},
	"setPolicyFile":                            {ID: "setPolicyFile", Method: "POST", Path: "/tailnet/{tailnet}/acl", Summary: "Set policy file"},
	"setSplitDns":                              {ID: "setSplitDns", Method: "PUT", Path: "/tailnet/{tailnet}/dns/split-dns", Summary: "Set split DNS"},
	"suspendUser":                              {ID: "suspendUser", Method: "POST", Path: "/users/{userId}/suspend", Summary: "Suspend a user"},
	"testWebhook":                              {ID: "testWebhook", Method: "POST", Path: "/webhooks/{endpointId}/test", Summary: "Test a webhook"},
	"updateContact":                            {ID: "updateContact", Method: "PATCH", Path: "/tailnet/{tailnet}/contacts/{contactType}", Summary: "Update contact"},
	"updateDeviceKey":                          {ID: "updateDeviceKey", Method: "POST", Path: "/device/{deviceId}/key", Summary: "Update device key"},
	"updateOAuthApp":                           {ID: "updateOAuthApp", Method: "PUT", Path: "/tailnet/{tailnet}/oauth-apps/{appId}", Summary: "Update OAuth app"},
	"updatePostureIntegration":                 {ID: "updatePostureIntegration", Method: "PATCH", Path: "/posture/integrations/{id}", Summary: "Update a posture integration"},
	"updateService":                            {ID: "updateService", Method: "PUT", Path: "/tailnet/{tailnet}/services/{serviceName}", Summary: "Update a Service"},
	"updateServiceDeviceApproval":              {ID: "updateServiceDeviceApproval", Method: "POST", Path: "/tailnet/{tailnet}/services/{serviceName}/device/{deviceId}/approved", Summary: "Update approval status of Service on a device"},
	"updateSplitDns":                           {ID: "updateSplitDns", Method: "PATCH", Path: "/tailnet/{tailnet}/dns/split-dns", Summary: "Update split DNS"},
	"updateTailnetSettings":                    {ID: "updateTailnetSettings", Method: "PATCH", Path: "/tailnet/{tailnet}/settings", Summary: "Update tailnet settings"},
	"updateUserRole":                           {ID: "updateUserRole", Method: "POST", Path: "/users/{userId}/role", Summary: "Update user role"},
	"updateWebhook":                            {ID: "updateWebhook", Method: "PATCH", Path: "/webhooks/{endpointId}", Summary: "Update webhook"},
	"validateAndTestPolicyFile":                {ID: "validateAndTestPolicyFile", Method: "POST", Path: "/tailnet/{tailnet}/acl/validate", Summary: "Validate and test policy file"},
	"validateAwsExternalId":                    {ID: "validateAwsExternalId", Method: "POST", Path: "/tailnet/{tailnet}/aws-external-id/{id}/validate-aws-trust-policy", Summary: "Validate external ID integration with IAM role trust policy"},
}

// Operations returns a copy so callers cannot mutate the catalogue.
func Operations() map[string]Operation {
	out := make(map[string]Operation, len(operations))
	for k, v := range operations {
		out[k] = v
	}
	return out
}
