package api

import _ "embed"

//go:embed schema.gen.json
var schemaDocument []byte

// SchemaDocument returns the pinned OpenAPI document as JSON for CLI validation.
// Generated by go generate; callers receive their own copy.
func SchemaDocument() []byte { return append([]byte(nil), schemaDocument...) }
