# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailctl" do
  on_macos do
    preflight_steps do
      run "/bin/sh",
          args: ["-c", 'set -eu; attributes=$(/usr/bin/xattr "$1"); if printf "%s\n" "$attributes" | /usr/bin/grep -Fxq com.apple.quarantine; then /usr/bin/xattr -d com.apple.quarantine "$1"; fi', "tailctl-quarantine", "{{staged_path}}/tailctl"],
          must_succeed: true
    end
  end

  version "0.0.5"

  on_macos do
    on_arm do
      sha256 "542685515445a9d4ca36f78a32035a4c0987087e5d61340cd1b73df7f8c3e347"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8d94adc2e794c0c7c3c53f464f3b1575dc1e7fe3421be31ca14d080c6426ee3"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77544717f89ff4268b019d0e5d076cc27b46bb3b3eb5e311edf1c22170f812d4"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "51cf6dd34ff58a37985f9d7a591c7b9e2bbb26a63094814f7458dd14ea3f8f30"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tailctl"
  desc "Extensible Tailscale API CLI with readable output and plugins"
  homepage "https://github.com/davidcollom/tailctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailctl"

  generate_completions_from_executable "tailctl",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
