# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailctl" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "42009d53ccfd73927ac1e9528383c3f4053df4f39626ebbae1aa8791ca4f2669"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2e51167d79358a79f022b829f99b5139c754a47396c94d73de430e371f8c062f"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1541c55744a7506fb6bf21ba42f6f8199fa5ae01b07d47d86c5c4b7a06843c69"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8dd5ad40dcd754c8f51f080bebf84b82b9505d2e76f86103dd9ade227dce811b"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tailctl"
  desc "Extensible Tailscale API CLI with readable output and plugins"
  homepage "https://github.com/davidcollom/tailctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/tailctl"], must_succeed: false
    end
  end
  generate_completions_from_executable "tailctl",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
