# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailctl" do
  on_macos do
    preflight_steps do
      run "/bin/sh",
          args: ["-c", 'set -eu; attributes=$(/usr/bin/xattr "$1"); if printf "%s\n" "$attributes" | /usr/bin/grep -Fxq com.apple.quarantine; then /usr/bin/xattr -d com.apple.quarantine "$1"; fi', "tailctl-quarantine", "{{staged_path}}/tailctl"],
          must_succeed: true
    end
  end

  version "0.0.4"

  on_macos do
    on_arm do
      sha256 "04ff1a9e49189d6319a9ba66674ef3245e9c0810b114a87a4b32200456e6eed7"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "74fbb15640da831b9e58f05b7a6ba5e2075aca08e462feeba16aed01ca2b820b"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "87e8442f999dcdea7ccc8b6a91a35b19e9e3339c2eb42bcaa2e4e7ae92e04958"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "317d389f437d36d649058659942d1f4783f2feec2773d3d9168c674e185e6cb4"
      url "https://github.com/davidcollom/tailctl/releases/download/v#{version}/tailctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tailctl"
  desc "Extensible Tailscale API CLI with readable output and plugins"
  homepage "https://github.com/davidcollom/tailctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailctl"

  generate_completions_from_executable "tailctl",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
