package cli

// ResourceBinding gives each upstream operation a stable, discoverable CLI path.
// New schema operations must be mapped here; coverage tests reject omissions.
type ResourceBinding struct{ Operation, Command string }

func ResourceBindings() []ResourceBinding {
	return []ResourceBinding{
		{"listTailnetDevices", "devices list"},
		{"getDevice", "devices get"},
		{"deleteDevice", "devices delete"},
		{"expireDeviceKey", "devices expire-key"},
		{"authorizeDevice", "devices authorise"},
		{"setDeviceName", "devices rename"},
		{"setDeviceTags", "devices tags set"},
		{"updateDeviceKey", "devices key update"},
		{"setDeviceIp", "devices ip set"},
		{"listDeviceRoutes", "devices routes get"},
		{"setDeviceRoutes", "devices routes set"},
		{"getDevicePostureAttributes", "devices attributes get"},
		{"setCustomDevicePostureAttributes", "devices attributes set"},
		{"deleteCustomDevicePostureAttributes", "devices attributes delete"},
		{"batchUpdateCustomDevicePostureAttributes", "devices attributes batch-update"},
		{"listUsers", "users list"},
		{"getUser", "users get"},
		{"updateUserRole", "users role set"},
		{"approveUser", "users approve"},
		{"suspendUser", "users suspend"},
		{"restoreUser", "users restore"},
		{"deleteUser", "users delete"},
		{"listDeviceInvites", "invites devices list"},
		{"createDeviceInvites", "invites devices create"},
		{"getDeviceInvite", "invites devices get"},
		{"deleteDeviceInvite", "invites devices delete"},
		{"resendDeviceInvite", "invites devices resend"},
		{"acceptDeviceInvite", "invites devices accept"},
		{"listUserInvites", "invites users list"},
		{"createUserInvites", "invites users create"},
		{"getUserInvite", "invites users get"},
		{"deleteUserInvite", "invites users delete"},
		{"resendUserInvite", "invites users resend"},
		{"listTailnetKeys", "keys list"},
		{"getKey", "keys get"},
		{"createKey", "keys create"},
		{"setKey", "keys update"},
		{"deleteKey", "keys delete"},
		{"getDnsConfiguration", "dns get"},
		{"setDnsConfiguration", "dns set"},
		{"listDnsNameservers", "dns nameservers get"},
		{"setDnsNameservers", "dns nameservers set"},
		{"getDnsPreferences", "dns preferences get"},
		{"setDnsPreferences", "dns preferences set"},
		{"listDnsSearchPaths", "dns search-paths get"},
		{"setDnsSearchPaths", "dns search-paths set"},
		{"getSplitDns", "dns split get"},
		{"setSplitDns", "dns split set"},
		{"updateSplitDns", "dns split update"},
		{"getPolicyFile", "policy get"},
		{"setPolicyFile", "policy set"},
		{"previewRuleMatches", "policy preview"},
		{"validateAndTestPolicyFile", "policy validate"},
		{"listConfigurationAuditLogs", "logs audit list"},
		{"listNetworkFlowLogs", "logs network list"},
		{"getLogStreamingStatus", "logs stream status"},
		{"getLogStreamingConfiguration", "logs stream get"},
		{"setLogStreamingConfiguration", "logs stream set"},
		{"disableLogStreaming", "logs stream disable"},
		{"getAwsExternalId", "logs aws-external-id create"},
		{"validateAwsExternalId", "logs aws-external-id validate"},
		{"getPostureIntegrations", "posture integrations list"},
		{"getPostureIntegration", "posture integrations get"},
		{"createPostureIntegration", "posture integrations create"},
		{"updatePostureIntegration", "posture integrations update"},
		{"deletePostureIntegration", "posture integrations delete"},
		{"getContacts", "contacts get"},
		{"updateContact", "contacts update"},
		{"resendContactVerificationEmail", "contacts resend-verification"},
		{"listWebhooks", "webhooks list"},
		{"getWebhook", "webhooks get"},
		{"createWebhook", "webhooks create"},
		{"updateWebhook", "webhooks update"},
		{"deleteWebhook", "webhooks delete"},
		{"testWebhook", "webhooks test"},
		{"rotateWebhookSecret", "webhooks rotate-secret"},
		{"getTailnetSettings", "settings get"},
		{"updateTailnetSettings", "settings update"},
		{"deleteTailnet", "tailnets delete"},
		{"listServices", "services list"},
		{"getService", "services get"},
		{"updateService", "services set"},
		{"deleteService", "services delete"},
		{"listServiceHosts", "services hosts list"},
		{"getServiceDeviceApproval", "services approval get"},
		{"updateServiceDeviceApproval", "services approval set"},
		{"listOAuthApps", "oauth-apps list"},
		{"getOAuthApp", "oauth-apps get"},
		{"createOAuthApp", "oauth-apps create"},
		{"updateOAuthApp", "oauth-apps update"},
		{"deleteOAuthApp", "oauth-apps delete"},
		{"listOrganizationTailnets", "organisations tailnets list"},
		{"createOrganizationTailnet", "organisations tailnets create"},
	}
}

// DeprecatedResourceBindings preserve command paths shipped before invites
// were consolidated under a single top-level command. They are intentionally
// excluded from schema coverage and generated documentation.
func DeprecatedResourceBindings() []ResourceBinding {
	return []ResourceBinding{
		{"listDeviceInvites", "devices invites list"},
		{"createDeviceInvites", "devices invites create"},
		{"listUserInvites", "user-invites list"},
		{"createUserInvites", "user-invites create"},
		{"getUserInvite", "user-invites get"},
		{"deleteUserInvite", "user-invites delete"},
		{"resendUserInvite", "user-invites resend"},
		{"getDeviceInvite", "device-invites get"},
		{"deleteDeviceInvite", "device-invites delete"},
		{"resendDeviceInvite", "device-invites resend"},
		{"acceptDeviceInvite", "device-invites accept"},
	}
}
