// Command generatedocs writes the resource reference from the real Cobra tree.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/davidcollom/tailctl/pkg/api"
	"github.com/davidcollom/tailctl/pkg/cli"
	"github.com/spf13/pflag"
)

func main() {
	root, err := cli.NewRoot(cli.Options{})
	if err != nil {
		panic(err)
	}
	var doc bytes.Buffer
	fmt.Fprintln(&doc, "# Resource command reference\n\nGenerated by `go generate ./...` from the pinned schema and Cobra command tree. Do not edit this file manually.\n\nEvery operation has a named resource command. Path IDs are positional; `--tailnet` supplies the tailnet. All non-GET/HEAD actions require `--yes`. Use `--file PATH` or `--file -` for complete bodies; JSON is validated locally. Body flags and `--file` are mutually exclusive. Repeat string-array flags, or use `--FIELD-json '[]'` to clear an array. Secret fields must be supplied through a body file/stdin.\n\nTables redact secrets. JSON/YAML preserve the full response, including pagination cursors and secrets. `--raw` writes exact response bytes. `--response-file PATH` reserves a new file before the request and saves exact bytes with mode 0600 on Unix; Windows uses the user's filesystem ACLs. Files are never overwritten. Lists make one request; follow cursor parameters explicitly when supported.\n\nUse `tailctl api describe OPERATION` for request/response schemas with all referenced components, without credentials. `tailctl api list` shows command mappings. The existing `get` helpers and generic `api call` remain available.")
	fmt.Fprintf(&doc, "\n## Coverage\n\n%d operations across %d command families.\n\n| Command | Operation | Method | Path |\n| --- | --- | --- | --- |\n", len(cli.ResourceBindings()), families())
	for _, binding := range cli.ResourceBindings() {
		op := api.Operations()[binding.Operation]
		fmt.Fprintf(&doc, "| `tailctl %s` | `%s` | %s | `%s` |\n", binding.Command, op.ID, op.Method, op.Path)
	}
	family := ""
	for _, binding := range cli.ResourceBindings() {
		words := strings.Fields(binding.Command)
		if words[0] != family {
			family = words[0]
			fmt.Fprintf(&doc, "\n## %s\n", family)
		}
		cmd, _, err := root.Find(words)
		if err != nil {
			panic(err)
		}
		op := api.Operations()[binding.Operation]
		fmt.Fprintf(&doc, "\n### %s\n\n%s\n\n```sh\n%s\n```\n\nOperation: `%s` · **%s** `%s`\n\n| Flag | Type | Description |\n| --- | --- | --- |\n", binding.Command, op.Summary, cmd.UseLine(), op.ID, op.Method, op.Path)
		cmd.Flags().VisitAll(func(flag *pflag.Flag) {
			fmt.Fprintf(&doc, "| `--%s` | `%s` | %s |\n", flag.Name, flag.Value.Type(), tableText(flag.Usage))
		})
	}
	fmt.Fprintln(&doc, "\n## Global flags\n\n| Flag | Type | Description |\n| --- | --- | --- |")
	root.PersistentFlags().VisitAll(func(flag *pflag.Flag) {
		fmt.Fprintf(&doc, "| `--%s` | `%s` | %s |\n", flag.Name, flag.Value.Type(), tableText(flag.Usage))
	})
	path := filepath.Join("..", "..", "docs", "commands.md")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, doc.Bytes(), 0644); err != nil {
		panic(err)
	}
}
func tableText(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", "\\|"), "\n", " ")
}
func families() int {
	seen := map[string]bool{}
	for _, binding := range cli.ResourceBindings() {
		seen[strings.Fields(binding.Command)[0]] = true
	}
	return len(seen)
}
